// Generated by jextract

package serial.ffm.linux;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = constants$14.const$2.varHandle(PathElement.groupElement("dcd"));
    static final VarHandle const$1 = constants$14.const$2.varHandle(PathElement.groupElement("rx"));
    static final VarHandle const$2 = constants$14.const$2.varHandle(PathElement.groupElement("tx"));
    static final VarHandle const$3 = constants$14.const$2.varHandle(PathElement.groupElement("frame"));
    static final VarHandle const$4 = constants$14.const$2.varHandle(PathElement.groupElement("overrun"));
    static final VarHandle const$5 = constants$14.const$2.varHandle(PathElement.groupElement("parity"));
}
