// Generated by jextract

package serial.ffm.linux;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$11.const$2.varHandle(PathElement.groupElement("irq"));
    static final VarHandle const$1 = constants$11.const$2.varHandle(PathElement.groupElement("flags"));
    static final VarHandle const$2 = constants$11.const$2.varHandle(PathElement.groupElement("xmit_fifo_size"));
    static final VarHandle const$3 = constants$11.const$2.varHandle(PathElement.groupElement("custom_divisor"));
    static final VarHandle const$4 = constants$11.const$2.varHandle(PathElement.groupElement("baud_base"));
    static final VarHandle const$5 = constants$11.const$2.varHandle(PathElement.groupElement("close_delay"));
}
