// Generated by jextract

package serial.ffm.linux;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final VarHandle const$0 = constants$14.const$2.varHandle(PathElement.groupElement("brk"));
    static final VarHandle const$1 = constants$14.const$2.varHandle(PathElement.groupElement("buf_overrun"));
    static final MemorySegment const$2 = MemorySegment.ofAddress(0L);
}
