// Generated by jextract

package serial.ffm.linux;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$11.const$2.varHandle(PathElement.groupElement("io_type"));
    static final VarHandle const$1 = constants$11.const$2.varHandle(PathElement.groupElement("hub6"));
    static final VarHandle const$2 = constants$11.const$2.varHandle(PathElement.groupElement("closing_wait"));
    static final VarHandle const$3 = constants$11.const$2.varHandle(PathElement.groupElement("closing_wait2"));
    static final VarHandle const$4 = constants$11.const$2.varHandle(PathElement.groupElement("iomem_base"));
    static final VarHandle const$5 = constants$11.const$2.varHandle(PathElement.groupElement("iomem_reg_shift"));
}
